name: Release workflow
on:
 push:
   tags:
    - "*"
permissions: 
 contents: write
jobs:
  release_workflow:
      name: "Release workflow"
      runs-on : ubuntu-latest
      steps:
        - name: "Action checkout"
          uses: actions/checkout@v3

        - name: "Action go"
          uses: actions/setup-go@v3
          with:
            go-version : '>=1.19.4'
            cache: true
        - name: "go releaser"
          uses: goreleaser/goreleaser-action@v4
          with:
            distribution: goreleaser
            version: latest
            args: release --rm-dist
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: "tag1"
          run: echo "${{github.ref_name}}"

        - name: "Action docker"
          uses: docker/setup-buildx-action@v2

        - name: "Login to Docker Hub"
          uses: docker/login-action@v2
          with: 
           username: ${{secrets.DOCKERHUB_USERNAME}}
           password: ${{secrets.DOCKERHUB_TOKEN}}
        -  name: Build and push
           uses: docker/build-push-action@v3
           with:
            push: true
            tags: